# fly.toml app configuration file generated for carq2 on 2023-09-05T16:02:20-05:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "carq2"
primary_region = "atl"

[deploy]
  release_command = "npm run seed"

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
